name: Automatic PR to master

on:
  workflow_dispatch:
  push:
    branches: [ "flutterflow" ]

jobs:
  create_pr:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 1000
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatic pull request
