name: Automatic PR to master

on:
  workflow_dispatch:
  push:
    branches: [ "flutterflow" ]

jobs:
  create_pr:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: flutterflow
          target_branch: master
          title: Automatic PR (merge flutterflow to master)
          body: "**Automated pull request**"
          get_diff: true
          ignore_users: "dependabot"
          allow_no_diff: true
