name: Build and push (PRE)

on:
  workflow_dispatch:
  push:
    branches: [ "development" ]

env:
  APP_NAME: "luncher-admin"
  ENV_SUFFIX: "-pre"


  DCKR_HUB_USER: "jewusiak"
  DCKR_HUB_REPO: "luncher"
  
  ENV_VARS_JSON: '
    {
      "backendurl": "https://api.pre1.luncher.pl",
      "importsbackendurl": "https://imports.api.pre.luncher.pl"
    }
    '

jobs:
  build_app:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup jq
        uses: vegardit/gha-setup-jq@v1
        
      - name: Override properties in environment.json
        run: | 
          echo '${{env.ENV_VARS_JSON}}' > .deployment/ovrrd.tmp.json
          bash .deployment/merge_jsons.sh assets/environment_values/environment.json .deployment/ovrrd.tmp.json assets/environment_values/environment.json
          mv assets/environment_values/environment2.json assets/environment_values/environment.json
      
      
      - name: Authenticate in Docker Hub
        run: 'docker login -u ${{env.DCKR_HUB_USER}} -p ${{ secrets.DCKR_HUB_PAT }}'

      - name: Build docker Image
        id: docker-build
        run: 'docker build -t ${{env.DCKR_HUB_USER}}/${{env.DCKR_HUB_REPO}}:${{ env.APP_NAME }}${{ env.ENV_SUFFIX }} --file=".deployment/Dockerfile-pre" .'

      - name: Push Docker image
        run: 'docker push ${{env.DCKR_HUB_USER}}/${{env.DCKR_HUB_REPO}}:${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}'
      