name: Build and push (PRO)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

env:
  APP_NAME: "luncher_admin_v4"
  ENV_SUFFIX: "-pro"


  DCKR_HUB_USER: "jewusiak"
  DCKR_HUB_REPO: "luncher"

jobs:
  build_app:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate in Docker Hub
        run: 'docker login -u ${{env.DCKR_HUB_USER}} -p ${{ secrets.DCKR_HUB_PAT }}'

      - name: Build docker Image
        id: docker-build
        run: 'docker build -t ${{env.DCKR_HUB_USER}}/${{env.DCKR_HUB_REPO}}:${{ env.APP_NAME }}${{ env.ENV_SUFFIX }} --file=".deployment/Dockerfile-pro" .'

      - name: Push Docker image
        run: 'docker push ${{env.DCKR_HUB_USER}}/${{env.DCKR_HUB_REPO}}:${{ env.APP_NAME }}${{ env.ENV_SUFFIX }}'
      